todoapp/todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todotask.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

todoapp/todoapp/todotask/urls.py
from django.urls import path

from . import views

app_name = 'todotask'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.Detail.as_view(), name='detail'),
    path('create/', views.create_task, name='create'),
    path('create/post', views.create_task_post, name='create_post'),
    path('<int:task_id>/finish', views.mark_as_finished, name='finish')
]

todoapp/todoapp/todotask/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.conf import settings

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    task_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    deadline = models.DateTimeField(default=timezone.now()+datetime.timedelta(weeks=1))
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.task_text

    def is_overdue(self):
        return self.deadline <= timezone.now()

    def is_finised(self):
        return self.finished

todoapp/todoapp/todotask/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


from django.views import generic
from django.utils import timezone

from .models import Task

LOGIN_URL = '/accounts/login'

@login_required(login_url=LOGIN_URL)
def index(request):
    relevant = Task.objects.order_by('-pub_date').filter(user=request.user, finished=False, deadline__gt=timezone.now())
    outdated = Task.objects.order_by('-pub_date').filter(user=request.user, finished=False, deadline__lt=timezone.now())
    finished = Task.objects.order_by('-pub_date').filter(user=request.user, finished=True)
    return render(request, 'todotask/index.html', {'relevant_tasks': relevant,
                                                   'outdated_tasks': outdated,
                                                   'finished_tasks': finished,})

class Detail(LoginRequiredMixin, generic.DetailView):
    login_url = LOGIN_URL

    model = Task
    template_name = 'todotask/detail.html'

@login_required(login_url=LOGIN_URL)
def create_task(request):
    return render(request, 'todotask/create.html', {})

@login_required(login_url=LOGIN_URL)
def create_task_post(request):
    new_task = Task(user=request.user)
    new_task.task_text = request.POST['task_text']
    if request.POST['deadline'] != '':
        new_task.deadline = request.POST['deadline']
    new_task.save()
    return HttpResponseRedirect(reverse('todotask:index'))

@login_required(login_url=LOGIN_URL)
def mark_as_finished(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.finished = True
    task.save()
    return HttpResponseRedirect(reverse('todotask:index'))

todoapp/todoapp/todotask/templates/todotask/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create task</title>
</head>
<body>
 <a href="{% url 'todotask:index' %}">Back</a> <br>
<h3>New task:</h3>
<br>
<form action="{% url 'todotask:create_post' %}" method="post">
{% csrf_token %}

<b>Task:</b> <input type="text" name="task_text" /> <br>
<b>Deadline:</b> <input type="datetime-local" name="deadline" /> <br>


<input type="submit" value="Create" />
</form>

</body>
</html>

todoapp/todoapp/todotask/templates/todotask/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task info</title>
</head>
<body>

{% if user == task.user %}

    <a href="{% url 'todotask:index' %}">Back</a> <br>

    <b>Task:</b> {{ task.task_text }}
    <br>
    <b>Created:</b> {{ task.pub_date }}
    <br>
    <b>Deadline:</b> {{ task.deadline }}
    <br>
    <b>Finished:</b> {{ task.finished }}
    <br>

<form action="{% url 'todotask:finish' task.id %}" method="post">
{% csrf_token %}

<input type="submit" value="Finish" />
</form>

{% else %}

    <h1>NO PERMISSION</h1>

{% endif %}

</body>
</html>

todoapp/todoapp/todotask/templates/todotask/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDo</title>
</head>
<body>

Welcome, {{  user.username  }} | <a href="{% url 'logout' %}">logout</a>
<br>
<a href="{% url 'todotask:create' %}">Create new task</a>

<h2> Relevant tasks </h2>
<ul>
    {% for task in relevant_tasks %}
        <li><a href="{% url 'todotask:detail' task.id %}">{{ task.task_text }}</a></li>
    {% endfor %}
</ul>

<h2> Outdated tasks </h2>
<ul>
    {% for task in outdated_tasks %}
        <li><a href="{% url 'todotask:detail' task.id %}">{{ task.task_text }}</a></li>
    {% endfor %}
</ul>

<h2> Finished tasks </h2>
<ul>
    {% for task in finished_tasks %}
        <li><a href="{% url 'todotask:detail' task.id %}">{{ task.task_text }}</a></li>
    {% endfor %}
</ul>

</body>
</html>